name: smart_kirana
description: "Vibrant Material 3 Cross-Platform Smart Kirana Client Store"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP Client & REST integration
  dio: ^5.4.0
  
  # Encripted Secure token storage
  flutter_secure_storage: ^9.0.0
  
  # Beautiful Material 3 UI assistants
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
